#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  namespace: argocd
  name: argocd-server-http
spec:
  virtualhost:
    fqdn: #@ "argocd.{}".format(data.values.ingress.domain)
    tls:
      secretName: #@ "{}/{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)
  routes:
    - services:
        - name: argocd-server
          port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  namespace: argocd
  name: argocd-server-cli
spec:
  virtualhost:
    fqdn: #@ "argocd-cli.{}".format(data.values.ingress.domain)
    tls:
      secretName: #@ "{}/{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)
  routes:
    - services:
        - name: argocd-server
          port: 443

#@ if data.values.psp.cluster_role:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argocd
  name: psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ data.values.psp.cluster_role
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
#@ end